# Generated by Django 2.1.7 on 2019-09-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('create_time', models.CharField(max_length=255)),
                ('perm_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nac',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostid', models.BigIntegerField()),
                ('ip', models.CharField(max_length=255)),
                ('mac', models.CharField(max_length=255)),
                ('dhcp_server', models.CharField(max_length=255)),
                ('dhcp_hostname', models.CharField(max_length=255)),
                ('nbtdomain', models.CharField(max_length=255)),
                ('ad_displayname', models.CharField(max_length=255)),
                ('ad_name', models.CharField(max_length=255)),
                ('ad_mail', models.CharField(max_length=255)),
                ('ad_title', models.CharField(max_length=255)),
                ('ad_department', models.CharField(max_length=255)),
                ('ad_mobile', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=255)),
                ('etag', models.CharField(max_length=255)),
                ('update_time', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Perm',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('describe', models.CharField(max_length=255)),
                ('code', models.IntegerField()),
            ],
        ),
    ]
